[tool.poetry]
name = "poetry env"
version = "0.1.0"
description = ""
authors = ["Вадим <kantora_70@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
